; ============================================================
; POC_ESP_2483 - ESP32-S3 + RN2483 LoRaWAN OTAA - Orange
; ============================================================
[platformio]
default_envs = esp32s3          ; pio run/upload ne cible que esp32s3 par défaut

[env:esp32s3]
platform   = espressif32            ; SDK Espressif (ESP-IDF + Arduino)
board      = esp32-s3-devkitc-1     ; carte cible
framework  = arduino                ; API Arduino sur ESP-IDF

monitor_speed = 115200              ; vitesse du terminal série

lib_deps =
  jpmeijers/RN2xx3 Arduino Library  ; communication UART avec le RN2483
  adafruit/Adafruit NeoPixel @ ^1.12.3 ; LED RGB WS2812 (GPIO48)

#build_type = debug                  ; inclut les symboles de débogage
#debug_tool = esp-builtin            ; JTAG intégré de l'ESP32-S3 via USB

build_flags =
  -DCORE_DEBUG_LEVEL=3              ; niveau de log ESP-IDF : INFO (0=off, 5=verbose)
  -DARDUINO_USB_CDC_ON_BOOT=1       ; Serial → USB CDC (port USB natif ESP32-S3)
  -DARDUINO_USB_MODE=1              ; mode USB CDC (requis avec le port USB natif)

[env:native]
platform = native                   ; tests unitaires exécutés sur le PC (pas de matériel)
test_build_project_src = no         ; ne pas compiler src/ (headers Arduino indisponibles en natif)
